//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HnPoc.DesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HnPoc.DesktopApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456789012.
        /// </summary>
        internal static string ItemBarcodeTemplate {
            get {
                return ResourceManager.GetString("ItemBarcodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Before: XX/XX/XXXX.
        /// </summary>
        internal static string ItemBestBeforeTemplate {
            get {
                return ResourceManager.GetString("ItemBestBeforeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XX Calories.
        /// </summary>
        internal static string ItemCaloriesTemplate {
            get {
                return ResourceManager.GetString("ItemCaloriesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrate4.
        /// </summary>
        internal static string ItemCarbohydratesTemplate {
            get {
                return ResourceManager.GetString("ItemCarbohydratesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy1kj / Energy2kcal.
        /// </summary>
        internal static string ItemEnergyTemplate {
            get {
                return ResourceManager.GetString("ItemEnergyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat2Fat2.
        /// </summary>
        internal static string ItemFatTemplate {
            get {
                return ResourceManager.GetString("ItemFatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibre6.
        /// </summary>
        internal static string ItemFibreTemplate {
            get {
                return ResourceManager.GetString("ItemFibreTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUID.
        /// </summary>
        internal static string ItemIngredientsTemplate {
            get {
                return ResourceManager.GetString("ItemIngredientsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.88.
        /// </summary>
        internal static string ItemPriceTemplate {
            get {
                return ResourceManager.GetString("ItemPriceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein6.
        /// </summary>
        internal static string ItemProteinTemplate {
            get {
                return ResourceManager.GetString("ItemProteinTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt7Salt7.
        /// </summary>
        internal static string ItemSaltTemplate {
            get {
                return ResourceManager.GetString("ItemSaltTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturates3.
        /// </summary>
        internal static string ItemSaturatesTemplate {
            get {
                return ResourceManager.GetString("ItemSaturatesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars5.
        /// </summary>
        internal static string ItemSugarsTemplate {
            get {
                return ResourceManager.GetString("ItemSugarsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Title.
        /// </summary>
        internal static string ItemTitleTemplate {
            get {
                return ResourceManager.GetString("ItemTitleTemplate", resourceCulture);
            }
        }
    }
}
